name: farmfinity_app
description: A Flutter E-Commerce app for Farmfinity
publish_to: 'none'

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  cached_network_image: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
  #   - assets/product_images/
  #   - assets/category_images/


